### ISSUE TITLE
对‘operator delete(void*, unsigned long)@CXXABI_1.3.9’未定义的引用

### ISSUE THREAD

**Issue by ggz21s** [haifengat/goctp#3]
$ go run main.go
go: downloading golang.org/x/text v0.3.4
   github.com/haifengat/goctp/lnx
../lnx/libctp_quote.so：对‘operator delete(void*, unsigned long)@CXXABI_1.3.9’未定义的引用
collect2: 错误：ld 返回 1

**Comment by haifengat** [comment]
我是在centos上测试的, 如果系统不同可能会有问题.

**Comment by haifengat** [comment]
最近在简化Docker发现busybox:glic的基础镜像中运行goctp需要以下文件在 /lib64下
libdl.so.2  libgcc_s.so.1  librt.so.1  libstdc++.so.6

**Comment by jonathanchoo519** [comment]
同CentOS，也是这个报错

**Comment by haifengat** [comment]
您好：

　　我这里没有出现， 可以从 hub.docker.com pull haifengat/go_real_md，测试。 也有可能是版本不同（我用的8.2），可以重新编译libctp_quote予以解决。



hubert28@qq.com
 
发件人： jonathanchoo519
发送时间： 2020-12-31 10:28
收件人： haifengat/goctp
抄送： 海风; Comment
主题： Re: [haifengat/goctp] 对‘operator delete(void*, unsigned long)@CXXABI_1.3.9’未定义的引用 (#3)
同CentOS，也是这个报错

**Comment by jonathanchoo519** [comment]
非常感谢，已经看到gitee的repo而且那边更新比较快。

看来解决跨平台依赖问题还是靠docker镜像啊！


在 2020年12月31日，下午4:35，海风 <notifications@github.com> 写道：

﻿

您好：

　　我这里没有出现， 可以从 hub.docker.com pull haifengat/go_real_md，测试。 也有可能是版本不同（我用的8.2），可以重新编译libctp_quote予以解决。



hubert28@qq.com

发件人： jonathanchoo519
发送时间： 2020-12-31 10:28
收件人： haifengat/goctp
抄送： 海风; Comment
主题： Re: [haifengat/goctp] 对‘operator delete(void*, unsigned long)@CXXABI_1.3.9’未定义的引用 (#3)
同CentOS，也是这个报错
