### ISSUE TITLE
是否现阶段可以用于生产环境呢？

### ISSUE THREAD

**Issue by qingwg** [haifengat/goctp#4]
你好，还没有测试使用，看到版本号是0.0.5.请问是否现阶段可以用于生产环境呢？

**Comment by haifengat** [comment]
不建议,目前只测了简单的行情的委托. 建议上生产前进行全面测试,包括资金权益,持仓中的数量,保证金等. 封装中做了一些计算处理,逻辑与python版本一致.

**Comment by qingwg** [comment]
好的，非常感谢
